
function action(clicked_id){
  var array_name1 = ["MHcvU3LLse","RAyZ9efDeF","BKrNt5cNnT","Fg4L4NCtWp","xNYfsk4mMH","jAiZiThtxT","Ppadbl3PQF","5lMwJLUjSe","rTdx52ENF4","5NNedUsR2J","UkfcVBmqqV","MXQgxJADXX","qMQaJdPkCO","RCui6qrFJV","HFCxKMvwYw","AkWbPQuXhf","MYZC9GqJ5W","6kzOuC9io4","TVdrILiBRE","a2nah2ZTfQ","NjgKucCGkx","rXF2MflLZM","JPJeu2PKGO","sRCeNTc6fI"];
  var array_name2 = ["2TLp2jJcXt","GHidcIuFNE","2YcMENmRch","byEObvxT6F","qEj29d92e5","L2ROWr2JdD","PL4euuRVIB","QEoKDw2gXS","zz4PAi3l4I","aPRtKZNW22","rDyVVOBg25","SKAV95g2eV","VrKe2gLHFh","pdzS5QasW9","XQ5A9bVRAL","GAAlvIt2u2","l9Dg3sdjP3","KPZCyfRgxV","c5IhB3a2Jm","rjLIzvtwsd","5YvuNldweV","lUCkFhq2u6","bCytPkgNWl","CAzA2c9f2O"];
  var array_name3 = ["L4gzYTWXpW","COInVs5Ga2","uYkiwAVHiW","Umu6GvW2ZK","9jwr3alYdl","DKRoajn4RN","IEjSYOa5th","9dTOkeBM25","UHDuUqhnLU","AvtlLELxIl","E2yC55SgEM","6tv9FdsIFg","5EbwufnHnw","2jDCwtJBS2","MBu2kwW2YW","2d95lsy2sR","z2doSNgnCF","24YoUx2HPI","z2gaaaCjDZ","5SJx2cuHdM","YcWEL52eyI","MjKvQDEoKR"];
  var array_name4 = ["p6I2wD5yA5","R22e4puqWX","jBXbnrOv5H","LvXmRK2SQY","yVYOvlm9ed","vL99aaWcRp","f2liClesiY","o22bmnnj5h","vi53jZkIXu","9mJNHsPwUm","mgfJMdCJ25","h9BL59JXms","zO22hjrNJL","tSMS9Qroor","XPHSWnZBga","5QRxnlhWek","ouaCZn2vFC","HNLMNNoF4V","9rOvIFyOQ9","xl222S3tzM","BxpXV9UJkP","62yVtgXKyt","yCLLncKn4f","hlfPDafq9G"];
  var array_name5 = ["2E2O0vVdgt","MpPy0tGef9","gsqK0wyj5e","ylTw0WgLIg","2OQA0MagWT","UZwG0cwM2k","bK6B0COkum","coDe0D9cNH","pnak0w3Qbq","jHf60Pxqc9","Fvtr0DLtHm","z4X50ZWfhW","Lj3M0tNmHn","6xsp0tWdOK","iGYn0g9lbt","djZi0kA9Qy","5yoF0ZEog9","eURY0uoQ6D","Jx6R0v2rBS","6bh20f35eG","9P5B0ghQaI","E2ZF0Ktel5","EkSc0bIJpQ","HhWw0VQQaL"];
  var array_name6 = ["xUG22vR2n6","At22vUzBTI","aI52kut25i","XdN2fww2tZ","tpc2o26Fbj","ss229ONlAW","2Am25n5mNM","I3W2Ds9kis","9262POSzKs","k5u2Qjm4rX","M9t26U9IFk","z3223Jm2KT","CJa2DrJmdI","Pyw2JO3ZMP","9px2WfeZvF","9q22LTMp2F","RQ92PHVlZs","TrK29PiM6C","rtF2ERB2t9","3l52gGAjZo","cnV2XOuOj9","sgr2BMu2nK","2Hf2Jdwz2q","qep2exRgO9"];
  var array_name7 = ["FdJE5o4IsH","h3IJHY42hv","62TfuZ4xsK","uKzK5s4oWr","5HEeeG4PEB","shrw9D4S33","s6KoKB4EZ9","KHkQYs4yPu","PRI2rd4Tig","Fg5pzZ49gK","sG5Mzq4awC","rdb2Vc425q","dHVDwK4c2X","tH6Vey43Gc","2uQeHw4Y2p","Z6suQx43U2","CcIvEn4uMG","vbqLCP4n5M","wx9I324ldW","AZGzzR4kxs","HWEdyC4QyJ","x9qiFx4P6K","WmDqX24rp4","Eg3zGz4I5X"];
  var array_name8 = ["Mimq5Jd29Y","q9rnJxcC9n","vr5CCH9692","lncO55Rp92","OntK4Dez9C","OwjIfbrf9j","35jhLml69g","IDizNMeF9D","6HQOIW5p93","J55Ttl4E9q","ubmnmwG29H","eddqpCbc9J","b2zMmTc29D","c9Ji9H2A9u","rERhnatB9f","Vz2dZere9N","B9x2wBtM9y","IST9Sh4t9b","4korrmKp9u","GIdHFXZd9f","VerroZG29B","FQmxu96K9C","2Wzm2rw29e"];
  var array_name9 = ["Fz36isCqNR","Zn56uzqnUM","RXF6pLdmmq","5W26l2fA4J","VhS655un9c","p9n6aAK2Ok","qAz62V45Ea","Esp6mWVGs5","df26sGurQx","Mo26ZnKjU5","3yn6VYrDFd","5sM6syh6n4","3p26KA92zO","reT6SZVv9h","N2G6PnDLow","3oT6NSG4E3","9s369WHgIy","DJ26IPgbVg","Q2P62vJrhp","xpu6wUw2j3","uV26E22hOt","Ink65uiaQg","Tee695cTvD","ZtL6mpG49i","aCk6H9if5v","hNl63N9aRI"];
  var array_name10 = ["9adVT3U2iz","2WuHK3rUz9","xJWok39495","kQgYk3vaMZ","Wil4o3Rsfv","AxDsg3AqHG","LdnYL3L52l","MK52R3tCUM","bDuWt35Nmz","URSot3uA5A","gFtoe332Ye","H6KQH3dQzU","stLvI3kxGa","MQ9Kx3ezcH","ut9aP3K2HZ","g6aQ932dnZ","gkfqd3afOe","nhnXB3KJkg","vtthS3ZkR6","j3nAo3yW2X","oMZwu3cKci","XfHRW3ibI9","CdvZH3RGp6","YR4jh3D594"];
  var array_name11 = ["29Nds25U34","69YN2RTTg5","N94K6us5aq","29LvXVO6vL","M9SfIYs2nX","a9XRD6y2l2","M99ok2vnEM","m9jlvs5U59","s9O9ntk66v","Z96HT6TkUz","m95q4H6heM","Y9UQIVeUY9","S92oy9Ui4D","299zLx2MBc","Q9cRCsbCv6","Y96UQZtqy2","r9qOqhpm2u","m9QLdCsQD2","D9Ok2DDPw3","S9xXkblyNY","f9vSBbqNMV","h93NKIZ2II","X9N2RBqu5f","o9ZRYdVLOM"];
  var array_name12 = ["A43g2yTizJ","xJB92BN9rM","99Ja2523fF","s2iO2HaGlK","oPjV2U9Zby","wMam2wgq5n","n5wR2nEghE","5d2N2uzwZP","bu2B2Xg2QR","CyGN2EhMtw","PpMp2wA2Fl","2Zdh22U3zu","X26e2Er6Vt","kuS22oc3GE","q6xF2FRcSn","JHAH2Pdvd9","jMmx2td4Mi","WcyK25MJuv","IYc22kK9tG","2rTy2jVsTY","Dwg62xu55Z","gLaD2tpZes"];
  var array_name13 = ["4FANMh59bM","EbM32c54FW","jnx5OY5J2M","HjXBnc5dhq","n3Ge4r5EvD","NHsxDO5WrV","n5bXd55NgC","x39tzL5y2H","YYRnt25M6Z","2nCe3O5dm3","ecnia2595l","vk2OdA5wzv","lS9JXa5Avt","U2RP9G5jIA","mYuZwT5FyV","rZdJNH5uFK","Jkjxoi5TaH","2E6IFE5z24","EuQZ9m59u9","nBUZ2y5fCC","Cp6tP55qaB","xAgsYn52M5","Lb5H2D5rsj","ZuFp2k5KP6"];
  var array_name14 = ["MeJ3h25Fz3","a493l9jwHR","QJb3c4snBY","6zW3Z9fCZv","qcw3p2eOWq","2343Q6HWWh","MT33kVvO2k","5Hn3CMr9sE","Y993AmChTb","A9N3tsTWJf","sc93qggK2M","ISs3c3lu9F","aw23ZqXvar","UVT3KUf9Po","Bgd33URFyW","64F3mCnN6y","E2D3c2U5to","r2x3B5TLEV","TH43fmhNhU","dXK3QzntFe","5X935ww29H","Wz232FBngS","Ub23Rb5OtV","zq9333JLCK","mvt3lVWw4V","U5x3pP4BgN"];
  var array_name15 = ["TqTHEoHP4V","2xV5xH2q4Q","qxyhdRcl4N","5f3zqjCp4V","NVBQ53mX4Z","m2FNVTB44L","Jymhx93r4v","5XPoKhp34Y","jSyRyU5i4w","fKg2gh2J4Q","boj5Kmvt4T","xscLFavt4B","BX6joqPU4K","LL6FIktR4r","QHXKsQXo4h","voS34jV24N","BD9w2F5z4k","L3hbXg6B4Q","vp3Bu5hS4P","fdfZ35ZP4P","2NzwmNUe4I","auhUlrcO4I","Ey5yvwFL4w"];
  var array_name16 = ["5262QMgJMR","tL6pVNp2p3","uW6hvlJYTS","5q6v45qXLt","LW6Zees2rh","Ln6rntePsf","jX6iqgwu2m","OO6cz2BBCh","4P6VECmhU9","CV64lcmpl2","dF6nmd9Nok","Dj6aqda3Lf","6g6iVK422K","F96kW3dXsf","vT6kcFcclu","vV6ZgCJUsE","Ad6s9aw9YM","bv6OFV9292","626xoXpy9f","hS6obgAIEX","Mc6L5Kwlsy","2I6GuI29Xe","3C65TQehHC"];
  var array_name17 = ["SBd590F9vR","GoQsg092iN","sHriE0Pize","pOrQb0LSUn","bNm5U0t36I","KLuAI0lVo2","eZs650hrHT","USKHN0SYMd","ueSCJ0iCUK","u5D9w06BGG","ghoDv0c2we","22ALB0XjIS","b5ZyZ06atd","atqDP0nics","OF9550I6Ze","WpeJW02ggA","ophkI0x9NM","bhqwA0uodl","qRX5b04uoS","hwfN60htYa","H2tkY0ol3q","fGJBj0PJia","pvTTo02DkC"];
  var array_name18 = ["pJbmktE222","QGZaK4BF2P","WV2rDnH62t","r3QOXMNo23","Td5Nq4ts2q","U6LyGudx2t","UvmS43z225","9Nawvcue22","NPbYYs6K2y","kqY4emzm2f","bAsKZ2H22J","gX2cS23A2Z","V65cop5i2x","x226jFOF2l","C3yGJKG52k","DX2xmCrK2l","eZz4C2Oe2o","xptxeK2I2W","FSt9fqDN2c","VQ4MZHMg2P","lldKoXAa23","eAcg5xNo29","45hqx6v32d","o2LJDodN22","XzCoTAU222","f9iF2E2m2u"];
  var array_name19 = ["s0AdyERPrR","K0c2ecoZX5","20L9xShDJu","h0IEW5PjoW","W05JqOtEx4","R0Xe6JWusC","N0nE2O2EmS","V0LE5Fmjsb","Z0QYkUa2Mm","y03tV6mWKN","j0n5GKqyXs","20lA4JSu5M","o0Rz24yEgd","B0Rw4RpRQg","60ffgSP5OE","50ZGyUg9W6","b0iYcHC4XH","K03ZGUkTiQ","n0JBCvr2oB","j02N22249k","G0L95iLRoC","w04wZro9Fc","P0Kepj6dIj"];
  var array_name20 = ["qx22sJoGZ2","p222QC2tsi","QM22pzgAcK","K622uctR9z","s222KWHrKY","Js225WOmDv","2U225ZvsN5","Aj222CoI5m","JY22Z42XN6","sX22kRMkGW","9P22XCnfVb","j522e2I2rZ","XS22XkH9bC","qg22k2xLwT","HN22NI3H53","AO22gzEqsT","LD22u9RPgF","od22pRl4mi","Pi226ROyjl","vy22SB5Nfu","9R22Bcm9EZ","kN22d3cYW5","vM22mP5TB2","MM226hpoih"];
  var array_name21 = ["g5Za643HDZ","oCrJe4gtaY","a2tmH4xz9o","y4e4Q42XsF","5OKEh44H3z","bsJJ34kLHY","XfBLd49i5M","3QrGe4FhyZ","vgrkj4CsZ9","yHLSe4AGIU","5em9l4fVTs","2FyKU4JVSl","u92tH492uX","Ao9Gn44C2w","95hJG4bpl4","v3TpO4P49b","rfEMU4kzKp","YbhFt4QHjj","IjXlj49ooo","iiyGh45JeI","3vjaz42Lfl","RHfwC4GS2y","sXOvi4sQXj","2QuGL49uzf","S2ret4eRMd","rBVc449LO6"];
  var array_name22 = ["Q2KvA6x99S","z65HgbU99C","2vvnqjA99l","VJcUiaC99G","9igwg3Q99o","udTnUZ499T","uSf9ZFm99e","GCeEvEH99g","ZRB2z9v99j","B96ZDYH99L","GV5B29A99B","Gxi5bQ699C","lds2CCC99G","SbMO9jQ99Q","ctPBz9v99G","2VVsqb999L","YckjkTM992","sWlMD2k99L","ezciAhy99M","jQRrCgP99E","tiOFPLO99v","5Oq9xnw99C","uD2v9s999F","vK9Ga2Z99U","dsqEyJ299C","UJTIFZR99I"];
  var array_name23 = ["d2hjdQg3n0","F6F3MCBrJ0","oNEAOalBp0","nnhifHpJp0","sUCWB6JoR0","9gObWcaTS0","xb2IOup420","h3Tpa9iGy0","FB29JzACt0","n5qzVHSCa0","693JxWUpu0","EtwQosado0","GQNEsXVdJ0","5weuAZ3hp0","KHgNRl2RB0","TmgFrXT9x0","9fJF5m56G0","v25kGp3fv0","DuiTVNmUB0","tdOXkorWq0","CCjtl5oE50","OHW2i2IY30","35aqj2WBt0","9nmFIuJNj0"];
  var array_name24 = ["Kj35pBe6vP","SB3kdre6uK","a43mUvW6w4","2f3Fhr96Do","vi3SKVD6ZA","uu33vfO6DQ","uo3i22x69E","gH35Cef6dW","cz35tW96sB","5p3dGmN6TR","TV3vFit65L","Lz3GKNi6vr","FK3Fydd6qy","as3qcNo6Ki","xX3xl2z6gT","Z63Emyz6HJ","Ty3gjkJ6Qy","ej30POm6Y5","Q536mVX6zQ","Wv3SwLc6tR","dM3FcNV6cP","UC3vSf269l"];
  var array_name25 = ["4Y0Ur2k39p","460D5n635E","M50GEEl3Au","Xi0iKMz3Xq","Vb0X25R3Ri","220gfCU3W2","XP0OVas3g5","Yy0mV9I3Jj","y30YsXE3ct","rP0XdAd3DW","Tr0RpCi32q","Fk0AD9L3z4","Cm02LPy3qq","BF0xLCf32w","Fz0QzVV3sh","9i0BDje35t","4d0SQQP3ZF","qT0XAqb3Rd","yJ0uneg3DP","s209sxE3lP","cz0kjAa3oF","CB0ZcxL3D3","Hz0eHuR3y3","ds0Iuc53jW"];
  var array_name26 = ["pWbViJyh62","wrlLyS5E62","AO9wgIzS62","ZG6BJNTT62","M2kK5VOY62","an5LZvmC62","biQkiJFO62","U3BltZG562","J2AUIMyX62","mZk3LYPa62","hCo5t9aQ62","k3NfMiCV62","9625JKtu62","TCXHWwCA62","gHjUTkan62","J9mMh5WL62","4obBcxfA62","65pztDbP62","gELbSgvT62","HECjIhIq62","jwuzj2MF62","t4AtMPTa62","2PwbssYW62","cBxQ2gLF62","BdEXsACf62","Oeu2FO9S62"];

  if(array_name1.includes(clicked_id)){
      reset(clicked_id);
  } else if(array_name2.includes(clicked_id)){
      reset(clicked_id);
  } else if(array_name3.includes(clicked_id)){
      reset(clicked_id);
  } else if(array_name4.includes(clicked_id)){
      reset(clicked_id);
  } else if(array_name5.includes(clicked_id)){
      reset(clicked_id);
  } else if(array_name6.includes(clicked_id)){
      reset(clicked_id);
  } else if(array_name7.includes(clicked_id)){
      reset(clicked_id);
  } else if(array_name8.includes(clicked_id)){
      reset(clicked_id);
  } else if(array_name9.includes(clicked_id)){
      reset(clicked_id);
  } else if(array_name10.includes(clicked_id)){
      reset(clicked_id);
  } else if(array_name11.includes(clicked_id)){
      reset(clicked_id);
  } else if(array_name12.includes(clicked_id)){
      reset(clicked_id);
  } else if(array_name13.includes(clicked_id)){
      reset(clicked_id);
  } else if(array_name14.includes(clicked_id)){
      reset(clicked_id);
  } else if(array_name15.includes(clicked_id)){
      reset(clicked_id);
  } else if(array_name16.includes(clicked_id)){
      reset(clicked_id);
  } else if(array_name17.includes(clicked_id)){
      reset(clicked_id);
  } else if(array_name18.includes(clicked_id)){
      reset(clicked_id);
  } else if(array_name19.includes(clicked_id)){
      reset(clicked_id);
  } else if(array_name20.includes(clicked_id)){
      reset(clicked_id);
  } else if(array_name21.includes(clicked_id)){
      reset(clicked_id);
  } else if(array_name22.includes(clicked_id)){
      reset(clicked_id);
  } else if(array_name23.includes(clicked_id)){
      reset(clicked_id);
  } else if(array_name24.includes(clicked_id)){
      reset(clicked_id);
  } else if(array_name25.includes(clicked_id)){
      reset(clicked_id);
  } else if(array_name26.includes(clicked_id)){
      reset(clicked_id);
  } else{
      trans(clicked_id);
  }
}

function trans(clicked_id){
  document.getElementById(clicked_id).className="gamebuttontrans";
}

function reset(clicked_id){
  document.getElementById("MHcvU3LLse").className="gamebutton";
  document.getElementById("RAyZ9efDeF").className="gamebutton";
  document.getElementById("BKrNt5cNnT").className="gamebutton";
  document.getElementById("Fg4L4NCtWp").className="gamebutton";
  document.getElementById("xNYfsk4mMH").className="gamebutton";
  document.getElementById("jAiZiThtxT").className="gamebutton";
  document.getElementById("Ppadbl3PQF").className="gamebutton";
  document.getElementById("5lMwJLUjSe").className="gamebutton";
  document.getElementById("rTdx52ENF4").className="gamebutton";
  document.getElementById("5NNedUsR2J").className="gamebutton";
  document.getElementById("UkfcVBmqqV").className="gamebutton";
  document.getElementById("MXQgxJADXX").className="gamebutton";
  document.getElementById("qMQaJdPkCO").className="gamebutton";
  document.getElementById("RCui6qrFJV").className="gamebutton";
  document.getElementById("HFCxKMvwYw").className="gamebutton";
  document.getElementById("YeQxdTHE1N").className="gamebutton";
  document.getElementById("a7WIaHbSyy").className="gamebutton";
  document.getElementById("AkWbPQuXhf").className="gamebutton";
  document.getElementById("MYZC9GqJ5W").className="gamebutton";
  document.getElementById("6kzOuC9io4").className="gamebutton";
  document.getElementById("TVdrILiBRE").className="gamebutton";
  document.getElementById("a2nah2ZTfQ").className="gamebutton";
  document.getElementById("NjgKucCGkx").className="gamebutton";
  document.getElementById("rXF2MflLZM").className="gamebutton";
  document.getElementById("JPJeu2PKGO").className="gamebutton";
  document.getElementById("sRCeNTc6fI").className="gamebutton";

  document.getElementById("2TLp2jJcXt").className="gamebutton";
	document.getElementById("GHidcIuFNE").className="gamebutton";
	document.getElementById("2YcMENmRch").className="gamebutton";
	document.getElementById("byEObvxT6F").className="gamebutton";
	document.getElementById("qEj29d92e5").className="gamebutton";
	document.getElementById("L2ROWr2JdD").className="gamebutton";
	document.getElementById("PL4euuRVIB").className="gamebutton";
	document.getElementById("QEoKDw2gXS").className="gamebutton";
	document.getElementById("zz4PAi3l4I").className="gamebutton";
	document.getElementById("aPRtKZNW22").className="gamebutton";
	document.getElementById("rDyVVOBg25").className="gamebutton";
	document.getElementById("SKAV95g2eV").className="gamebutton";
	document.getElementById("VrKe2gLHFh").className="gamebutton";
	document.getElementById("pdzS5QasW9").className="gamebutton";
	document.getElementById("XQ5A9bVRAL").className="gamebutton";
	document.getElementById("xXtaATAn8o").className="gamebutton";
	document.getElementById("xCT1BfiHvv").className="gamebutton";
	document.getElementById("GAAlvIt2u2").className="gamebutton";
	document.getElementById("l9Dg3sdjP3").className="gamebutton";
	document.getElementById("KPZCyfRgxV").className="gamebutton";
	document.getElementById("c5IhB3a2Jm").className="gamebutton";
	document.getElementById("rjLIzvtwsd").className="gamebutton";
	document.getElementById("5YvuNldweV").className="gamebutton";
	document.getElementById("lUCkFhq2u6").className="gamebutton";
	document.getElementById("bCytPkgNWl").className="gamebutton";
	document.getElementById("CAzA2c9f2O").className="gamebutton";

  document.getElementById("L4gzYTWXpW").className="gamebutton";
	document.getElementById("COInVs5Ga2").className="gamebutton";
	document.getElementById("uYkiwAVHiW").className="gamebutton";
	document.getElementById("uSykDkT75q").className="gamebutton";
	document.getElementById("BX2iq8iQil").className="gamebutton";
	document.getElementById("Umu6GvW2ZK").className="gamebutton";
	document.getElementById("9jwr3alYdl").className="gamebutton";
	document.getElementById("DKRoajn4RN").className="gamebutton";
	document.getElementById("IEjSYOa5th").className="gamebutton";
	document.getElementById("9dTOkeBM25").className="gamebutton";
	document.getElementById("UHDuUqhnLU").className="gamebutton";
	document.getElementById("AvtlLELxIl").className="gamebutton";
	document.getElementById("E2yC55SgEM").className="gamebutton";
	document.getElementById("6tv9FdsIFg").className="gamebutton";
	document.getElementById("5EbwufnHnw").className="gamebutton";
	document.getElementById("IV1hGFOHKW").className="gamebutton";
	document.getElementById("ykR7Agzr95").className="gamebutton";
	document.getElementById("2jDCwtJBS2").className="gamebutton";
	document.getElementById("MBu2kwW2YW").className="gamebutton";
	document.getElementById("2d95lsy2sR").className="gamebutton";
	document.getElementById("z2doSNgnCF").className="gamebutton";
	document.getElementById("24YoUx2HPI").className="gamebutton";
	document.getElementById("z2gaaaCjDZ").className="gamebutton";
	document.getElementById("5SJx2cuHdM").className="gamebutton";
	document.getElementById("YcWEL52eyI").className="gamebutton";
	document.getElementById("MjKvQDEoKR").className="gamebutton";

  document.getElementById("p6I2wD5yA5").className="gamebutton";
	document.getElementById("R22e4puqWX").className="gamebutton";
	document.getElementById("jBXbnrOv5H").className="gamebutton";
	document.getElementById("vVe1JldOUL").className="gamebutton";
	document.getElementById("wNPJ7FJ5PS").className="gamebutton";
	document.getElementById("LvXmRK2SQY").className="gamebutton";
	document.getElementById("yVYOvlm9ed").className="gamebutton";
	document.getElementById("vL99aaWcRp").className="gamebutton";
	document.getElementById("f2liClesiY").className="gamebutton";
	document.getElementById("o22bmnnj5h").className="gamebutton";
	document.getElementById("vi53jZkIXu").className="gamebutton";
	document.getElementById("9mJNHsPwUm").className="gamebutton";
	document.getElementById("mgfJMdCJ25").className="gamebutton";
	document.getElementById("h9BL59JXms").className="gamebutton";
	document.getElementById("zO22hjrNJL").className="gamebutton";
	document.getElementById("tSMS9Qroor").className="gamebutton";
	document.getElementById("XPHSWnZBga").className="gamebutton";
	document.getElementById("5QRxnlhWek").className="gamebutton";
	document.getElementById("ouaCZn2vFC").className="gamebutton";
	document.getElementById("HNLMNNoF4V").className="gamebutton";
	document.getElementById("9rOvIFyOQ9").className="gamebutton";
	document.getElementById("xl222S3tzM").className="gamebutton";
	document.getElementById("BxpXV9UJkP").className="gamebutton";
	document.getElementById("62yVtgXKyt").className="gamebutton";
	document.getElementById("yCLLncKn4f").className="gamebutton";
	document.getElementById("hlfPDafq9G").className="gamebutton";

  document.getElementById("2E2O0vVdgt").className="gamebutton";
	document.getElementById("MpPy0tGef9").className="gamebutton";
	document.getElementById("gsqK0wyj5e").className="gamebutton";
	document.getElementById("ylTw0WgLIg").className="gamebutton";
	document.getElementById("2OQA0MagWT").className="gamebutton";
	document.getElementById("UZwG0cwM2k").className="gamebutton";
	document.getElementById("bK6B0COkum").className="gamebutton";
	document.getElementById("coDe0D9cNH").className="gamebutton";
	document.getElementById("pnak0w3Qbq").className="gamebutton";
	document.getElementById("jHf60Pxqc9").className="gamebutton";
	document.getElementById("Fvtr0DLtHm").className="gamebutton";
	document.getElementById("z4X50ZWfhW").className="gamebutton";
	document.getElementById("Lj3M0tNmHn").className="gamebutton";
	document.getElementById("6xsp0tWdOK").className="gamebutton";
	document.getElementById("iGYn0g9lbt").className="gamebutton";
	document.getElementById("djZi0kA9Qy").className="gamebutton";
	document.getElementById("5yoF0ZEog9").className="gamebutton";
	document.getElementById("eURY0uoQ6D").className="gamebutton";
	document.getElementById("Jx6R0v2rBS").className="gamebutton";
	document.getElementById("6bh20f35eG").className="gamebutton";
	document.getElementById("9P5B0ghQaI").className="gamebutton";
	document.getElementById("E2ZF0Ktel5").className="gamebutton";
	document.getElementById("NAdv0In8er").className="gamebutton";
	document.getElementById("rd210XiXNz").className="gamebutton";
	document.getElementById("EkSc0bIJpQ").className="gamebutton";
	document.getElementById("HhWw0VQQaL").className="gamebutton";

  document.getElementById("xUG22vR2n6").className="gamebutton";
	document.getElementById("At22vUzBTI").className="gamebutton";
	document.getElementById("aI52kut25i").className="gamebutton";
	document.getElementById("XdN2fww2tZ").className="gamebutton";
	document.getElementById("tpc2o26Fbj").className="gamebutton";
	document.getElementById("ss229ONlAW").className="gamebutton";
	document.getElementById("2Am25n5mNM").className="gamebutton";
	document.getElementById("I3W2Ds9kis").className="gamebutton";
	document.getElementById("9262POSzKs").className="gamebutton";
	document.getElementById("k5u2Qjm4rX").className="gamebutton";
	document.getElementById("M9t26U9IFk").className="gamebutton";
	document.getElementById("z3223Jm2KT").className="gamebutton";
	document.getElementById("CJa2DrJmdI").className="gamebutton";
	document.getElementById("Pyw2JO3ZMP").className="gamebutton";
	document.getElementById("9px2WfeZvF").className="gamebutton";
	document.getElementById("9q22LTMp2F").className="gamebutton";
	document.getElementById("RQ92PHVlZs").className="gamebutton";
	document.getElementById("TrK29PiM6C").className="gamebutton";
	document.getElementById("rtF2ERB2t9").className="gamebutton";
	document.getElementById("3l52gGAjZo").className="gamebutton";
	document.getElementById("cnV2XOuOj9").className="gamebutton";
	document.getElementById("sgr2BMu2nK").className="gamebutton";
	document.getElementById("Sya7OGYPg5").className="gamebutton";
	document.getElementById("rYl86fPTcb").className="gamebutton";
	document.getElementById("2Hf2Jdwz2q").className="gamebutton";
	document.getElementById("qep2exRgO9").className="gamebutton";

  document.getElementById("FdJE5o4IsH").className="gamebutton";
	document.getElementById("h3IJHY42hv").className="gamebutton";
	document.getElementById("62TfuZ4xsK").className="gamebutton";
	document.getElementById("uKzK5s4oWr").className="gamebutton";
	document.getElementById("5HEeeG4PEB").className="gamebutton";
	document.getElementById("shrw9D4S33").className="gamebutton";
	document.getElementById("s6KoKB4EZ9").className="gamebutton";
	document.getElementById("4YCqkb8vkx").className="gamebutton";
	document.getElementById("wT2R7d46bc").className="gamebutton";
	document.getElementById("KHkQYs4yPu").className="gamebutton";
	document.getElementById("PRI2rd4Tig").className="gamebutton";
	document.getElementById("Fg5pzZ49gK").className="gamebutton";
	document.getElementById("sG5Mzq4awC").className="gamebutton";
	document.getElementById("rdb2Vc425q").className="gamebutton";
	document.getElementById("dHVDwK4c2X").className="gamebutton";
	document.getElementById("tH6Vey43Gc").className="gamebutton";
	document.getElementById("2uQeHw4Y2p").className="gamebutton";
	document.getElementById("Z6suQx43U2").className="gamebutton";
	document.getElementById("CcIvEn4uMG").className="gamebutton";
	document.getElementById("vbqLCP4n5M").className="gamebutton";
	document.getElementById("wx9I324ldW").className="gamebutton";
	document.getElementById("AZGzzR4kxs").className="gamebutton";
	document.getElementById("HWEdyC4QyJ").className="gamebutton";
	document.getElementById("x9qiFx4P6K").className="gamebutton";
	document.getElementById("WmDqX24rp4").className="gamebutton";
	document.getElementById("Eg3zGz4I5X").className="gamebutton";

  document.getElementById("Mimq5Jd29Y").className="gamebutton";
	document.getElementById("q9rnJxcC9n").className="gamebutton";
	document.getElementById("vr5CCH9692").className="gamebutton";
	document.getElementById("lncO55Rp92").className="gamebutton";
	document.getElementById("OntK4Dez9C").className="gamebutton";
	document.getElementById("OwjIfbrf9j").className="gamebutton";
	document.getElementById("35jhLml69g").className="gamebutton";
	document.getElementById("ViMvMA1m9D").className="gamebutton";
	document.getElementById("ZYRMh7K39O").className="gamebutton";
	document.getElementById("IDizNMeF9D").className="gamebutton";
	document.getElementById("6HQOIW5p93").className="gamebutton";
	document.getElementById("J55Ttl4E9q").className="gamebutton";
	document.getElementById("ubmnmwG29H").className="gamebutton";
	document.getElementById("eddqpCbc9J").className="gamebutton";
	document.getElementById("b2zMmTc29D").className="gamebutton";
	document.getElementById("c9Ji9H2A9u").className="gamebutton";
	document.getElementById("B2x2N8Ws9T").className="gamebutton";
	document.getElementById("rERhnatB9f").className="gamebutton";
	document.getElementById("Vz2dZere9N").className="gamebutton";
	document.getElementById("B9x2wBtM9y").className="gamebutton";
	document.getElementById("IST9Sh4t9b").className="gamebutton";
	document.getElementById("4korrmKp9u").className="gamebutton";
	document.getElementById("GIdHFXZd9f").className="gamebutton";
	document.getElementById("VerroZG29B").className="gamebutton";
	document.getElementById("FQmxu96K9C").className="gamebutton";
	document.getElementById("2Wzm2rw29e").className="gamebutton";

  document.getElementById("Fz36isCqNR").className="gamebutton";
	document.getElementById("Zn56uzqnUM").className="gamebutton";
	document.getElementById("RXF6pLdmmq").className="gamebutton";
	document.getElementById("5W26l2fA4J").className="gamebutton";
	document.getElementById("VhS655un9c").className="gamebutton";
	document.getElementById("p9n6aAK2Ok").className="gamebutton";
	document.getElementById("qAz62V45Ea").className="gamebutton";
	document.getElementById("Esp6mWVGs5").className="gamebutton";
	document.getElementById("df26sGurQx").className="gamebutton";
	document.getElementById("Mo26ZnKjU5").className="gamebutton";
	document.getElementById("3yn6VYrDFd").className="gamebutton";
	document.getElementById("5sM6syh6n4").className="gamebutton";
	document.getElementById("3p26KA92zO").className="gamebutton";
	document.getElementById("reT6SZVv9h").className="gamebutton";
	document.getElementById("N2G6PnDLow").className="gamebutton";
	document.getElementById("3oT6NSG4E3").className="gamebutton";
	document.getElementById("9s369WHgIy").className="gamebutton";
	document.getElementById("DJ26IPgbVg").className="gamebutton";
	document.getElementById("Q2P62vJrhp").className="gamebutton";
	document.getElementById("xpu6wUw2j3").className="gamebutton";
	document.getElementById("uV26E22hOt").className="gamebutton";
	document.getElementById("Ink65uiaQg").className="gamebutton";
	document.getElementById("Tee695cTvD").className="gamebutton";
	document.getElementById("ZtL6mpG49i").className="gamebutton";
	document.getElementById("aCk6H9if5v").className="gamebutton";
	document.getElementById("hNl63N9aRI").className="gamebutton";

  document.getElementById("9adVT3U2iz").className="gamebutton";
	document.getElementById("2WuHK3rUz9").className="gamebutton";
	document.getElementById("xJWok39495").className="gamebutton";
	document.getElementById("kQgYk3vaMZ").className="gamebutton";
	document.getElementById("Wil4o3Rsfv").className="gamebutton";
	document.getElementById("AxDsg3AqHG").className="gamebutton";
	document.getElementById("LdnYL3L52l").className="gamebutton";
	document.getElementById("MK52R3tCUM").className="gamebutton";
	document.getElementById("bDuWt35Nmz").className="gamebutton";
	document.getElementById("URSot3uA5A").className="gamebutton";
	document.getElementById("gFtoe332Ye").className="gamebutton";
	document.getElementById("H6KQH3dQzU").className="gamebutton";
	document.getElementById("stLvI3kxGa").className="gamebutton";
	document.getElementById("MQ9Kx3ezcH").className="gamebutton";
	document.getElementById("ut9aP3K2HZ").className="gamebutton";
	document.getElementById("g6aQ932dnZ").className="gamebutton";
	document.getElementById("gkfqd3afOe").className="gamebutton";
	document.getElementById("nhnXB3KJkg").className="gamebutton";
	document.getElementById("vtthS3ZkR6").className="gamebutton";
	document.getElementById("j3nAo3yW2X").className="gamebutton";
	document.getElementById("oMZwu3cKci").className="gamebutton";
	document.getElementById("Fp1Ym3LTxs").className="gamebutton";
	document.getElementById("dfOVw3AM8u").className="gamebutton";
	document.getElementById("XfHRW3ibI9").className="gamebutton";
	document.getElementById("CdvZH3RGp6").className="gamebutton";
	document.getElementById("YR4jh3D594").className="gamebutton";

  document.getElementById("29Nds25U34").className="gamebutton";
	document.getElementById("69YN2RTTg5").className="gamebutton";
	document.getElementById("N94K6us5aq").className="gamebutton";
	document.getElementById("29LvXVO6vL").className="gamebutton";
	document.getElementById("M9SfIYs2nX").className="gamebutton";
	document.getElementById("a9XRD6y2l2").className="gamebutton";
	document.getElementById("M99ok2vnEM").className="gamebutton";
	document.getElementById("m9jlvs5U59").className="gamebutton";
	document.getElementById("s9O9ntk66v").className="gamebutton";
	document.getElementById("Z96HT6TkUz").className="gamebutton";
	document.getElementById("m95q4H6heM").className="gamebutton";
	document.getElementById("Y9UQIVeUY9").className="gamebutton";
	document.getElementById("S92oy9Ui4D").className="gamebutton";
	document.getElementById("299zLx2MBc").className="gamebutton";
	document.getElementById("Q9cRCsbCv6").className="gamebutton";
	document.getElementById("Y96UQZtqy2").className="gamebutton";
	document.getElementById("r9qOqhpm2u").className="gamebutton";
	document.getElementById("m9QLdCsQD2").className="gamebutton";
	document.getElementById("D9Ok2DDPw3").className="gamebutton";
	document.getElementById("S9xXkblyNY").className="gamebutton";
	document.getElementById("f9vSBbqNMV").className="gamebutton";
	document.getElementById("k9WJZWZwc7").className="gamebutton";
	document.getElementById("69Pkqq1aOj").className="gamebutton";
	document.getElementById("h93NKIZ2II").className="gamebutton";
	document.getElementById("X9N2RBqu5f").className="gamebutton";
	document.getElementById("o9ZRYdVLOM").className="gamebutton";

  document.getElementById("A43g2yTizJ").className="gamebutton";
	document.getElementById("xJB92BN9rM").className="gamebutton";
	document.getElementById("aX2o2mu8SD").className="gamebutton";
	document.getElementById("9dl52toh1M").className="gamebutton";
	document.getElementById("99Ja2523fF").className="gamebutton";
	document.getElementById("s2iO2HaGlK").className="gamebutton";
	document.getElementById("oPjV2U9Zby").className="gamebutton";
	document.getElementById("wMam2wgq5n").className="gamebutton";
	document.getElementById("n5wR2nEghE").className="gamebutton";
	document.getElementById("5d2N2uzwZP").className="gamebutton";
	document.getElementById("bu2B2Xg2QR").className="gamebutton";
	document.getElementById("CyGN2EhMtw").className="gamebutton";
	document.getElementById("PpMp2wA2Fl").className="gamebutton";
	document.getElementById("2Zdh22U3zu").className="gamebutton";
	document.getElementById("X26e2Er6Vt").className="gamebutton";
	document.getElementById("kuS22oc3GE").className="gamebutton";
	document.getElementById("q6xF2FRcSn").className="gamebutton";
	document.getElementById("JHAH2Pdvd9").className="gamebutton";
	document.getElementById("jMmx2td4Mi").className="gamebutton";
	document.getElementById("WcyK25MJuv").className="gamebutton";
	document.getElementById("IYc22kK9tG").className="gamebutton";
	document.getElementById("tJZr2U1IjQ").className="gamebutton";
	document.getElementById("qz7E2ptifd").className="gamebutton";
	document.getElementById("2rTy2jVsTY").className="gamebutton";
	document.getElementById("Dwg62xu55Z").className="gamebutton";
	document.getElementById("gLaD2tpZes").className="gamebutton";

  document.getElementById("4FANMh59bM").className="gamebutton";
	document.getElementById("EbM32c54FW").className="gamebutton";
	document.getElementById("J1BllY5VGs").className="gamebutton";
	document.getElementById("RuY5xq5i8X").className="gamebutton";
	document.getElementById("jnx5OY5J2M").className="gamebutton";
	document.getElementById("HjXBnc5dhq").className="gamebutton";
	document.getElementById("n3Ge4r5EvD").className="gamebutton";
	document.getElementById("NHsxDO5WrV").className="gamebutton";
	document.getElementById("n5bXd55NgC").className="gamebutton";
	document.getElementById("x39tzL5y2H").className="gamebutton";
	document.getElementById("YYRnt25M6Z").className="gamebutton";
	document.getElementById("2nCe3O5dm3").className="gamebutton";
	document.getElementById("ecnia2595l").className="gamebutton";
	document.getElementById("vk2OdA5wzv").className="gamebutton";
	document.getElementById("lS9JXa5Avt").className="gamebutton";
	document.getElementById("U2RP9G5jIA").className="gamebutton";
	document.getElementById("mYuZwT5FyV").className="gamebutton";
	document.getElementById("rZdJNH5uFK").className="gamebutton";
	document.getElementById("Jkjxoi5TaH").className="gamebutton";
	document.getElementById("2E6IFE5z24").className="gamebutton";
	document.getElementById("EuQZ9m59u9").className="gamebutton";
	document.getElementById("nBUZ2y5fCC").className="gamebutton";
	document.getElementById("Cp6tP55qaB").className="gamebutton";
	document.getElementById("xAgsYn52M5").className="gamebutton";
	document.getElementById("Lb5H2D5rsj").className="gamebutton";
	document.getElementById("ZuFp2k5KP6").className="gamebutton";

  document.getElementById("MeJ3h25Fz3").className="gamebutton";
	document.getElementById("a493l9jwHR").className="gamebutton";
	document.getElementById("QJb3c4snBY").className="gamebutton";
	document.getElementById("6zW3Z9fCZv").className="gamebutton";
	document.getElementById("qcw3p2eOWq").className="gamebutton";
	document.getElementById("2343Q6HWWh").className="gamebutton";
	document.getElementById("MT33kVvO2k").className="gamebutton";
	document.getElementById("5Hn3CMr9sE").className="gamebutton";
	document.getElementById("Y993AmChTb").className="gamebutton";
	document.getElementById("A9N3tsTWJf").className="gamebutton";
	document.getElementById("sc93qggK2M").className="gamebutton";
	document.getElementById("ISs3c3lu9F").className="gamebutton";
	document.getElementById("aw23ZqXvar").className="gamebutton";
	document.getElementById("UVT3KUf9Po").className="gamebutton";
	document.getElementById("Bgd33URFyW").className="gamebutton";
	document.getElementById("64F3mCnN6y").className="gamebutton";
	document.getElementById("E2D3c2U5to").className="gamebutton";
	document.getElementById("r2x3B5TLEV").className="gamebutton";
	document.getElementById("TH43fmhNhU").className="gamebutton";
	document.getElementById("dXK3QzntFe").className="gamebutton";
	document.getElementById("5X935ww29H").className="gamebutton";
	document.getElementById("Wz232FBngS").className="gamebutton";
	document.getElementById("Ub23Rb5OtV").className="gamebutton";
	document.getElementById("zq9333JLCK").className="gamebutton";
	document.getElementById("mvt3lVWw4V").className="gamebutton";
	document.getElementById("U5x3pP4BgN").className="gamebutton";

  document.getElementById("TqTHEoHP4V").className="gamebutton";
	document.getElementById("2xV5xH2q4Q").className="gamebutton";
	document.getElementById("qxyhdRcl4N").className="gamebutton";
	document.getElementById("5f3zqjCp4V").className="gamebutton";
	document.getElementById("NVBQ53mX4Z").className="gamebutton";
	document.getElementById("m2FNVTB44L").className="gamebutton";
	document.getElementById("Jymhx93r4v").className="gamebutton";
	document.getElementById("5XPoKhp34Y").className="gamebutton";
	document.getElementById("jSyRyU5i4w").className="gamebutton";
	document.getElementById("fKg2gh2J4Q").className="gamebutton";
	document.getElementById("boj5Kmvt4T").className="gamebutton";
	document.getElementById("pGC8np5L42").className="gamebutton";
	document.getElementById("nwcA21pF4R").className="gamebutton";
	document.getElementById("a7Gl63p24Q").className="gamebutton";
	document.getElementById("xscLFavt4B").className="gamebutton";
	document.getElementById("BX6joqPU4K").className="gamebutton";
	document.getElementById("LL6FIktR4r").className="gamebutton";
	document.getElementById("QHXKsQXo4h").className="gamebutton";
	document.getElementById("voS34jV24N").className="gamebutton";
	document.getElementById("BD9w2F5z4k").className="gamebutton";
	document.getElementById("L3hbXg6B4Q").className="gamebutton";
	document.getElementById("vp3Bu5hS4P").className="gamebutton";
	document.getElementById("fdfZ35ZP4P").className="gamebutton";
	document.getElementById("2NzwmNUe4I").className="gamebutton";
	document.getElementById("auhUlrcO4I").className="gamebutton";
	document.getElementById("Ey5yvwFL4w").className="gamebutton";

  document.getElementById("5262QMgJMR").className="gamebutton";
	document.getElementById("tL6pVNp2p3").className="gamebutton";
	document.getElementById("uW6hvlJYTS").className="gamebutton";
	document.getElementById("5q6v45qXLt").className="gamebutton";
	document.getElementById("LW6Zees2rh").className="gamebutton";
	document.getElementById("Ln6rntePsf").className="gamebutton";
	document.getElementById("jX6iqgwu2m").className="gamebutton";
	document.getElementById("OO6cz2BBCh").className="gamebutton";
	document.getElementById("4P6VECmhU9").className="gamebutton";
	document.getElementById("CV64lcmpl2").className="gamebutton";
	document.getElementById("dF6nmd9Nok").className="gamebutton";
	document.getElementById("c96F1oiBd9").className="gamebutton";
	document.getElementById("6V6F97xOn2").className="gamebutton";
	document.getElementById("AZ68dvc5ZB").className="gamebutton";
	document.getElementById("Dj6aqda3Lf").className="gamebutton";
	document.getElementById("6g6iVK422K").className="gamebutton";
	document.getElementById("F96kW3dXsf").className="gamebutton";
	document.getElementById("vT6kcFcclu").className="gamebutton";
	document.getElementById("vV6ZgCJUsE").className="gamebutton";
	document.getElementById("Ad6s9aw9YM").className="gamebutton";
	document.getElementById("bv6OFV9292").className="gamebutton";
	document.getElementById("626xoXpy9f").className="gamebutton";
	document.getElementById("hS6obgAIEX").className="gamebutton";
	document.getElementById("Mc6L5Kwlsy").className="gamebutton";
	document.getElementById("2I6GuI29Xe").className="gamebutton";
	document.getElementById("3C65TQehHC").className="gamebutton";

  document.getElementById("SBd590F9vR").className="gamebutton";
	document.getElementById("GoQsg092iN").className="gamebutton";
	document.getElementById("sHriE0Pize").className="gamebutton";
	document.getElementById("pOrQb0LSUn").className="gamebutton";
	document.getElementById("bNm5U0t36I").className="gamebutton";
	document.getElementById("KLuAI0lVo2").className="gamebutton";
	document.getElementById("eZs650hrHT").className="gamebutton";
	document.getElementById("USKHN0SYMd").className="gamebutton";
	document.getElementById("ueSCJ0iCUK").className="gamebutton";
	document.getElementById("u5D9w06BGG").className="gamebutton";
	document.getElementById("ghoDv0c2we").className="gamebutton";
	document.getElementById("NS12H0vWgX").className="gamebutton";
	document.getElementById("WWx2R0Hxa8").className="gamebutton";
	document.getElementById("PW7G30Yn3M").className="gamebutton";
	document.getElementById("22ALB0XjIS").className="gamebutton";
	document.getElementById("b5ZyZ06atd").className="gamebutton";
	document.getElementById("atqDP0nics").className="gamebutton";
	document.getElementById("OF9550I6Ze").className="gamebutton";
	document.getElementById("WpeJW02ggA").className="gamebutton";
	document.getElementById("ophkI0x9NM").className="gamebutton";
	document.getElementById("bhqwA0uodl").className="gamebutton";
	document.getElementById("qRX5b04uoS").className="gamebutton";
	document.getElementById("hwfN60htYa").className="gamebutton";
	document.getElementById("H2tkY0ol3q").className="gamebutton";
	document.getElementById("fGJBj0PJia").className="gamebutton";
	document.getElementById("pvTTo02DkC").className="gamebutton";

  document.getElementById("pJbmktE222").className="gamebutton";
	document.getElementById("QGZaK4BF2P").className="gamebutton";
	document.getElementById("WV2rDnH62t").className="gamebutton";
	document.getElementById("r3QOXMNo23").className="gamebutton";
	document.getElementById("Td5Nq4ts2q").className="gamebutton";
	document.getElementById("U6LyGudx2t").className="gamebutton";
	document.getElementById("UvmS43z225").className="gamebutton";
	document.getElementById("9Nawvcue22").className="gamebutton";
	document.getElementById("NPbYYs6K2y").className="gamebutton";
	document.getElementById("kqY4emzm2f").className="gamebutton";
	document.getElementById("bAsKZ2H22J").className="gamebutton";
	document.getElementById("gX2cS23A2Z").className="gamebutton";
	document.getElementById("V65cop5i2x").className="gamebutton";
	document.getElementById("x226jFOF2l").className="gamebutton";
	document.getElementById("C3yGJKG52k").className="gamebutton";
	document.getElementById("DX2xmCrK2l").className="gamebutton";
	document.getElementById("eZz4C2Oe2o").className="gamebutton";
	document.getElementById("xptxeK2I2W").className="gamebutton";
	document.getElementById("FSt9fqDN2c").className="gamebutton";
	document.getElementById("VQ4MZHMg2P").className="gamebutton";
	document.getElementById("lldKoXAa23").className="gamebutton";
	document.getElementById("eAcg5xNo29").className="gamebutton";
	document.getElementById("45hqx6v32d").className="gamebutton";
	document.getElementById("o2LJDodN22").className="gamebutton";
	document.getElementById("XzCoTAU222").className="gamebutton";
	document.getElementById("f9iF2E2m2u").className="gamebutton";

  document.getElementById("P0JNYJe1TD").className="gamebutton";
	document.getElementById("s0AdyERPrR").className="gamebutton";
	document.getElementById("K0c2ecoZX5").className="gamebutton";
	document.getElementById("20L9xShDJu").className="gamebutton";
	document.getElementById("h0IEW5PjoW").className="gamebutton";
	document.getElementById("W05JqOtEx4").className="gamebutton";
	document.getElementById("R0Xe6JWusC").className="gamebutton";
	document.getElementById("N0nE2O2EmS").className="gamebutton";
	document.getElementById("V0LE5Fmjsb").className="gamebutton";
	document.getElementById("Z0QYkUa2Mm").className="gamebutton";
	document.getElementById("y03tV6mWKN").className="gamebutton";
	document.getElementById("j0n5GKqyXs").className="gamebutton";
	document.getElementById("20lA4JSu5M").className="gamebutton";
	document.getElementById("o0Rz24yEgd").className="gamebutton";
	document.getElementById("B0Rw4RpRQg").className="gamebutton";
	document.getElementById("60ffgSP5OE").className="gamebutton";
	document.getElementById("50ZGyUg9W6").className="gamebutton";
	document.getElementById("b0iYcHC4XH").className="gamebutton";
	document.getElementById("309FRp28YB").className="gamebutton";
	document.getElementById("w0whu273mY").className="gamebutton";
	document.getElementById("K03ZGUkTiQ").className="gamebutton";
	document.getElementById("n0JBCvr2oB").className="gamebutton";
	document.getElementById("j02N22249k").className="gamebutton";
	document.getElementById("G0L95iLRoC").className="gamebutton";
	document.getElementById("w04wZro9Fc").className="gamebutton";
	document.getElementById("P0Kepj6dIj").className="gamebutton";

  document.getElementById("qx22sJoGZ2").className="gamebutton";
	document.getElementById("p222QC2tsi").className="gamebutton";
	document.getElementById("QM22pzgAcK").className="gamebutton";
	document.getElementById("K622uctR9z").className="gamebutton";
	document.getElementById("s222KWHrKY").className="gamebutton";
	document.getElementById("Js225WOmDv").className="gamebutton";
	document.getElementById("2U225ZvsN5").className="gamebutton";
	document.getElementById("Aj222CoI5m").className="gamebutton";
	document.getElementById("JY22Z42XN6").className="gamebutton";
	document.getElementById("sX22kRMkGW").className="gamebutton";
	document.getElementById("9P22XCnfVb").className="gamebutton";
	document.getElementById("j522e2I2rZ").className="gamebutton";
	document.getElementById("XS22XkH9bC").className="gamebutton";
	document.getElementById("qg22k2xLwT").className="gamebutton";
	document.getElementById("HN22NI3H53").className="gamebutton";
	document.getElementById("AO22gzEqsT").className="gamebutton";
	document.getElementById("LD22u9RPgF").className="gamebutton";
	document.getElementById("od22pRl4mi").className="gamebutton";
	document.getElementById("mK22Pjs7aI").className="gamebutton";
	document.getElementById("Lj224F28lE").className="gamebutton";
	document.getElementById("Pi226ROyjl").className="gamebutton";
	document.getElementById("vy22SB5Nfu").className="gamebutton";
	document.getElementById("9R22Bcm9EZ").className="gamebutton";
	document.getElementById("kN22d3cYW5").className="gamebutton";
	document.getElementById("vM22mP5TB2").className="gamebutton";
	document.getElementById("MM226hpoih").className="gamebutton";

  document.getElementById("g5Za643HDZ").className="gamebutton";
	document.getElementById("oCrJe4gtaY").className="gamebutton";
	document.getElementById("a2tmH4xz9o").className="gamebutton";
	document.getElementById("y4e4Q42XsF").className="gamebutton";
	document.getElementById("5OKEh44H3z").className="gamebutton";
	document.getElementById("bsJJ34kLHY").className="gamebutton";
	document.getElementById("XfBLd49i5M").className="gamebutton";
	document.getElementById("3QrGe4FhyZ").className="gamebutton";
	document.getElementById("vgrkj4CsZ9").className="gamebutton";
	document.getElementById("yHLSe4AGIU").className="gamebutton";
	document.getElementById("5em9l4fVTs").className="gamebutton";
	document.getElementById("2FyKU4JVSl").className="gamebutton";
	document.getElementById("u92tH492uX").className="gamebutton";
	document.getElementById("Ao9Gn44C2w").className="gamebutton";
	document.getElementById("95hJG4bpl4").className="gamebutton";
	document.getElementById("v3TpO4P49b").className="gamebutton";
	document.getElementById("rfEMU4kzKp").className="gamebutton";
	document.getElementById("YbhFt4QHjj").className="gamebutton";
	document.getElementById("IjXlj49ooo").className="gamebutton";
	document.getElementById("iiyGh45JeI").className="gamebutton";
	document.getElementById("3vjaz42Lfl").className="gamebutton";
	document.getElementById("RHfwC4GS2y").className="gamebutton";
	document.getElementById("sXOvi4sQXj").className="gamebutton";
	document.getElementById("2QuGL49uzf").className="gamebutton";
	document.getElementById("S2ret4eRMd").className="gamebutton";
	document.getElementById("rBVc449LO6").className="gamebutton";

  document.getElementById("Q2KvA6x99S").className="gamebutton";
	document.getElementById("z65HgbU99C").className="gamebutton";
	document.getElementById("2vvnqjA99l").className="gamebutton";
	document.getElementById("VJcUiaC99G").className="gamebutton";
	document.getElementById("9igwg3Q99o").className="gamebutton";
	document.getElementById("udTnUZ499T").className="gamebutton";
	document.getElementById("uSf9ZFm99e").className="gamebutton";
	document.getElementById("GCeEvEH99g").className="gamebutton";
	document.getElementById("ZRB2z9v99j").className="gamebutton";
	document.getElementById("B96ZDYH99L").className="gamebutton";
	document.getElementById("GV5B29A99B").className="gamebutton";
	document.getElementById("Gxi5bQ699C").className="gamebutton";
	document.getElementById("lds2CCC99G").className="gamebutton";
	document.getElementById("SbMO9jQ99Q").className="gamebutton";
	document.getElementById("ctPBz9v99G").className="gamebutton";
	document.getElementById("2VVsqb999L").className="gamebutton";
	document.getElementById("YckjkTM992").className="gamebutton";
	document.getElementById("sWlMD2k99L").className="gamebutton";
	document.getElementById("ezciAhy99M").className="gamebutton";
	document.getElementById("jQRrCgP99E").className="gamebutton";
	document.getElementById("tiOFPLO99v").className="gamebutton";
	document.getElementById("5Oq9xnw99C").className="gamebutton";
	document.getElementById("uD2v9s999F").className="gamebutton";
	document.getElementById("vK9Ga2Z99U").className="gamebutton";
	document.getElementById("dsqEyJ299C").className="gamebutton";
	document.getElementById("UJTIFZR99I").className="gamebutton";

  document.getElementById("d2hjdQg3n0").className="gamebutton";
	document.getElementById("F6F3MCBrJ0").className="gamebutton";
	document.getElementById("oNEAOalBp0").className="gamebutton";
	document.getElementById("nnhifHpJp0").className="gamebutton";
	document.getElementById("sUCWB6JoR0").className="gamebutton";
	document.getElementById("W8vfgbA2r0").className="gamebutton";
	document.getElementById("Jt9AI91520").className="gamebutton";
	document.getElementById("9gObWcaTS0").className="gamebutton";
	document.getElementById("xb2IOup420").className="gamebutton";
	document.getElementById("h3Tpa9iGy0").className="gamebutton";
	document.getElementById("FB29JzACt0").className="gamebutton";
	document.getElementById("n5qzVHSCa0").className="gamebutton";
	document.getElementById("693JxWUpu0").className="gamebutton";
	document.getElementById("EtwQosado0").className="gamebutton";
	document.getElementById("GQNEsXVdJ0").className="gamebutton";
	document.getElementById("5weuAZ3hp0").className="gamebutton";
	document.getElementById("KHgNRl2RB0").className="gamebutton";
	document.getElementById("TmgFrXT9x0").className="gamebutton";
	document.getElementById("9fJF5m56G0").className="gamebutton";
	document.getElementById("v25kGp3fv0").className="gamebutton";
	document.getElementById("DuiTVNmUB0").className="gamebutton";
	document.getElementById("tdOXkorWq0").className="gamebutton";
	document.getElementById("CCjtl5oE50").className="gamebutton";
	document.getElementById("OHW2i2IY30").className="gamebutton";
	document.getElementById("35aqj2WBt0").className="gamebutton";
	document.getElementById("9nmFIuJNj0").className="gamebutton";

  document.getElementById("Kj35pBe6vP").className="gamebutton";
	document.getElementById("SB3kdre6uK").className="gamebutton";
	document.getElementById("a43mUvW6w4").className="gamebutton";
	document.getElementById("2f3Fhr96Do").className="gamebutton";
	document.getElementById("vi3SKVD6ZA").className="gamebutton";
	document.getElementById("Ap31TVE6oZ").className="gamebutton";
	document.getElementById("ns37A2W6DK").className="gamebutton";
	document.getElementById("uu33vfO6DQ").className="gamebutton";
	document.getElementById("uo3i22x69E").className="gamebutton";
	document.getElementById("gH35Cef6dW").className="gamebutton";
	document.getElementById("cz35tW96sB").className="gamebutton";
	document.getElementById("5p3dGmN6TR").className="gamebutton";
	document.getElementById("TV3vFit65L").className="gamebutton";
	document.getElementById("Lz3GKNi6vr").className="gamebutton";
	document.getElementById("FK3Fydd6qy").className="gamebutton";
	document.getElementById("as3qcNo6Ki").className="gamebutton";
	document.getElementById("xX3xl2z6gT").className="gamebutton";
	document.getElementById("Z63Emyz6HJ").className="gamebutton";
	document.getElementById("Ty3gjkJ6Qy").className="gamebutton";
	document.getElementById("HT372qV6uq").className="gamebutton";
	document.getElementById("cz38Qa46BJ").className="gamebutton";
	document.getElementById("ej30POm6Y5").className="gamebutton";
	document.getElementById("Q536mVX6zQ").className="gamebutton";
	document.getElementById("Wv3SwLc6tR").className="gamebutton";
	document.getElementById("dM3FcNV6cP").className="gamebutton";
	document.getElementById("UC3vSf269l").className="gamebutton";

  document.getElementById("4Y0Ur2k39p").className="gamebutton";
	document.getElementById("460D5n635E").className="gamebutton";
	document.getElementById("M50GEEl3Au").className="gamebutton";
	document.getElementById("Xi0iKMz3Xq").className="gamebutton";
	document.getElementById("Vb0X25R3Ri").className="gamebutton";
	document.getElementById("220gfCU3W2").className="gamebutton";
	document.getElementById("XP0OVas3g5").className="gamebutton";
	document.getElementById("Yy0mV9I3Jj").className="gamebutton";
	document.getElementById("y30YsXE3ct").className="gamebutton";
	document.getElementById("rP0XdAd3DW").className="gamebutton";
	document.getElementById("Tr0RpCi32q").className="gamebutton";
	document.getElementById("Fk0AD9L3z4").className="gamebutton";
	document.getElementById("Cm02LPy3qq").className="gamebutton";
	document.getElementById("BF0xLCf32w").className="gamebutton";
	document.getElementById("Fz0QzVV3sh").className="gamebutton";
	document.getElementById("9i0BDje35t").className="gamebutton";
	document.getElementById("4d0SQQP3ZF").className="gamebutton";
	document.getElementById("qT0XAqb3Rd").className="gamebutton";
	document.getElementById("yJ0uneg3DP").className="gamebutton";
	document.getElementById("Tt0rc1E3r9").className="gamebutton";
	document.getElementById("RT0Xd8X3aO").className="gamebutton";
	document.getElementById("s209sxE3lP").className="gamebutton";
	document.getElementById("cz0kjAa3oF").className="gamebutton";
	document.getElementById("CB0ZcxL3D3").className="gamebutton";
	document.getElementById("Hz0eHuR3y3").className="gamebutton";
	document.getElementById("ds0Iuc53jW").className="gamebutton";

  document.getElementById("pWbViJyh62").className="gamebutton";
	document.getElementById("wrlLyS5E62").className="gamebutton";
	document.getElementById("AO9wgIzS62").className="gamebutton";
	document.getElementById("ZG6BJNTT62").className="gamebutton";
	document.getElementById("M2kK5VOY62").className="gamebutton";
	document.getElementById("an5LZvmC62").className="gamebutton";
	document.getElementById("biQkiJFO62").className="gamebutton";
	document.getElementById("U3BltZG562").className="gamebutton";
	document.getElementById("J2AUIMyX62").className="gamebutton";
	document.getElementById("mZk3LYPa62").className="gamebutton";
	document.getElementById("hCo5t9aQ62").className="gamebutton";
	document.getElementById("k3NfMiCV62").className="gamebutton";
	document.getElementById("9625JKtu62").className="gamebutton";
	document.getElementById("TCXHWwCA62").className="gamebutton";
	document.getElementById("gHjUTkan62").className="gamebutton";
	document.getElementById("J9mMh5WL62").className="gamebutton";
	document.getElementById("4obBcxfA62").className="gamebutton";
	document.getElementById("65pztDbP62").className="gamebutton";
	document.getElementById("gELbSgvT62").className="gamebutton";
	document.getElementById("HECjIhIq62").className="gamebutton";
	document.getElementById("jwuzj2MF62").className="gamebutton";
	document.getElementById("t4AtMPTa62").className="gamebutton";
	document.getElementById("2PwbssYW62").className="gamebutton";
	document.getElementById("cBxQ2gLF62").className="gamebutton";
	document.getElementById("BdEXsACf62").className="gamebutton";
	document.getElementById("Oeu2FO9S62").className="gamebutton";










}
